site_name: Keyes Cloud Solutions Portfolio
site_description: Cloud + DevSecOps portfolio by Charles "Chuck" Keyes Sr.
site_url: https://<your-username>.github.io/<your-repo>
theme:
  name: material
  features:
    - navigation.sections
    - navigation.tracking
    - content.code.copy
    - content.code.annotate
    - toc.integrate
  language: en
  palette:
    - scheme: default
nav:
  - Home: index.md
  - Projects:
      - NCC Hub & Global Spokes: projects/ncc-global-hub.md
      - AWS <-> GCP HA-VPN (Terraform): projects/aws-gcp-ha-vpn.md
      - BigQuery + DLP (Terraform): projects/bigquery-dlp.md
  - About: about.md
markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - footnotes
  - toc:
      permalink: true
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/<your-username>
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/<your-handle>/